#!/bin/sh
#
# Make a dump of all MySQL databases.

# Only do the dump when MySQL is running
/etc/init.d/mysql status > /dev/null || exit 0

set -e

# Secure umask
umask 027

# Create a new directory for the backups if it doesn't exist.
[ -d /var/backups/mysql ] || mkdir -p /var/backups/mysql
chown root:adm /var/backups/mysql
chmod 2750 /var/backups/mysql

# Remove old backups completely.
rm -rf /var/backups/mysql/*

# Get the databases defined in MySQL. Disregard the information_schema database.
DBS=`/usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf -e "show databases\G" \
     | /bin/grep -v ^* | /usr/bin/awk '{print $2}' | /bin/grep -v ^information_schema$ \
     | /bin/grep -v ^performance_schema$`

# Actually backup each database.
for db in $DBS; do
/usr/bin/mysqldump --defaults-file=/etc/mysql/debian.cnf --routines --opt --max-allowed-packet=1G \
	--ignore-table=mysql.events --force --quote-names --quick $db | \
	/bin/gzip -9 --rsyncable > /var/backups/mysql/$db.sql.gz
done
